CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null,
    age int check (age > 1920)
);
CREATE TABLE Address(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(id) on delete cascade,
    address varchar(100) not null,
    country varchar(100) not null
);